export enum ContentEnum {
  all = "all",
  post = "post",
  unPost = "unPost",
  userPost = "userPost",
  video = "video",
  unVideo = "unVideo",
  article = "article",
  unArticle = "unArticle",
  tag = "tag",
  tagPost = "tagPost",
  tagArticle = "tagArticle",
  tagVideo = "tagVideo",
  user = "user",
}
